name: CI

on:
  push:
  pull_request:
    types: [opened, synchronize, closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run linting
      run: |
        chmod +x gradlew
        ./gradlew ktlintCheck
    - name: Run tests
      run: ./gradlew check jacocoTestReport
    - name: Upload coverage report
      if: success()
      run: bash <(curl -s https://codecov.io/bash)